<a href="https://colab.research.google.com/github/RajeevRanjany/100DaysML/blob/main/Numpy_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [92]:
import numpy as np

In [104]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

In [108]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [106]:
type(arr)

numpy.ndarray

In [118]:
np.arange(1,11,1).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [129]:
np.linspace(-1,10,10, dtype = int)

array([-1,  0,  1,  2,  3,  5,  6,  7,  8, 10])

In [122]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [123]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [128]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [130]:
arr.ndim

2

Array Funtions

In [145]:
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,91]
])



In [133]:
b = a*2

In [135]:
b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [140]:
a - b

array([[-1, -2, -3],
       [-4, -5, -6],
       [-7, -8, -9]])

In [143]:
a.ndim

2

In [153]:
a.max()

np.int64(91)

In [157]:
# 0 -> column and 1 -> row
a.sum(axis=1)

array([  6,  15, 106])

In [160]:
a.mean()

np.float64(14.11111111111111)

In [162]:
np.median(a)

np.float64(5.0)

In [165]:
np.var(a,dtype=int)

np.int64(743)

In [167]:
np.dot(a,b)

array([[  60,   72,   84],
       [ 132,  162,  192],
       [1352, 1564, 1776]])

indexing and slicing

In [170]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [173]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [171]:
a1[-1]

np.int64(9)

In [172]:
a1[0]

np.int64(0)

In [174]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [178]:
a2[1,2]

np.int64(6)

In [180]:
a2[1,0]

np.int64(4)

In [181]:
# 3d
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [183]:
a3[0,0,0]

np.int64(0)

Slicing

In [184]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [185]:
a1[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [189]:
a1[2:5]

array([2, 3, 4])

In [190]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [194]:
a2[0]

array([0, 1, 2, 3])

In [195]:
a2[0,:]

array([0, 1, 2, 3])

In [197]:
a2[:,2]

array([ 2,  6, 10])

In [198]:
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [204]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [211]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [213]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [214]:
a4 = np.arange(27).reshape(3,3,3)

In [215]:
a4

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [221]:
a4[0,1,:]

array([3, 4, 5])

In [222]:
a4[1,:,1]

array([10, 13, 16])

In [231]:
a4[2,1:3,1:3]

array([[22, 23],
       [25, 26]])

Itrating

In [232]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [236]:
for i in a2 :
  print(a2)
  print()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



In [235]:
for i in a3:
  print(i)
  print()

[[0 1]
 [2 3]]

[[4 5]
 [6 7]]



In [237]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7


In [240]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

Horizontal Stacking

In [242]:
a5 = np.arange(12).reshape(3,4)
a6 = np.arange(12,24).reshape(3,4)

In [243]:
np.hstack((a5,a6))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

Vertical Stacking

In [244]:
np.vstack((a5,a6))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Spitting : hsptting and vSpitting

In [248]:
a5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [247]:
np.hsplit(a5,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]